// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdftohtml.proto

package com.datasahi.pdftohtml.grpc;

/**
 * <pre>
 * The service definition.
 * </pre>
 *
 * Protobuf service {@code pdftohtml.ConvertPdfToHtml}
 */
public  abstract class ConvertPdfToHtml
    implements com.google.protobuf.Service {
  protected ConvertPdfToHtml() {}

  public interface Interface {
    /**
     * <code>rpc PdfToHtml(.pdftohtml.Request) returns (.pdftohtml.Reply);</code>
     */
    public abstract void pdfToHtml(
        com.google.protobuf.RpcController controller,
        com.datasahi.pdftohtml.grpc.Request request,
        com.google.protobuf.RpcCallback<com.datasahi.pdftohtml.grpc.Reply> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new ConvertPdfToHtml() {
      @java.lang.Override
      public  void pdfToHtml(
          com.google.protobuf.RpcController controller,
          com.datasahi.pdftohtml.grpc.Request request,
          com.google.protobuf.RpcCallback<com.datasahi.pdftohtml.grpc.Reply> done) {
        impl.pdfToHtml(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.pdfToHtml(controller, (com.datasahi.pdftohtml.grpc.Request)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.datasahi.pdftohtml.grpc.Request.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.datasahi.pdftohtml.grpc.Reply.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc PdfToHtml(.pdftohtml.Request) returns (.pdftohtml.Reply);</code>
   */
  public abstract void pdfToHtml(
      com.google.protobuf.RpcController controller,
      com.datasahi.pdftohtml.grpc.Request request,
      com.google.protobuf.RpcCallback<com.datasahi.pdftohtml.grpc.Reply> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.datasahi.pdftohtml.grpc.PdfToHtmlProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.pdfToHtml(controller, (com.datasahi.pdftohtml.grpc.Request)request,
          com.google.protobuf.RpcUtil.<com.datasahi.pdftohtml.grpc.Reply>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.datasahi.pdftohtml.grpc.Request.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.datasahi.pdftohtml.grpc.Reply.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.datasahi.pdftohtml.grpc.ConvertPdfToHtml implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void pdfToHtml(
        com.google.protobuf.RpcController controller,
        com.datasahi.pdftohtml.grpc.Request request,
        com.google.protobuf.RpcCallback<com.datasahi.pdftohtml.grpc.Reply> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.datasahi.pdftohtml.grpc.Reply.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.datasahi.pdftohtml.grpc.Reply.class,
          com.datasahi.pdftohtml.grpc.Reply.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.datasahi.pdftohtml.grpc.Reply pdfToHtml(
        com.google.protobuf.RpcController controller,
        com.datasahi.pdftohtml.grpc.Request request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.datasahi.pdftohtml.grpc.Reply pdfToHtml(
        com.google.protobuf.RpcController controller,
        com.datasahi.pdftohtml.grpc.Request request)
        throws com.google.protobuf.ServiceException {
      return (com.datasahi.pdftohtml.grpc.Reply) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.datasahi.pdftohtml.grpc.Reply.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:pdftohtml.ConvertPdfToHtml)
}

