// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdftohtml.proto

package com.datasahi.pdftohtml.grpc;

public final class PdfToHtmlProto {
  private PdfToHtmlProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pdftohtml_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pdftohtml_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pdftohtml_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pdftohtml_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017pdftohtml.proto\022\tpdftohtml\"@\n\007Request\022" +
      "\016\n\006source\030\001 \001(\t\022\023\n\013destination\030\002 \001(\t\022\020\n\010" +
      "password\030\003 \001(\t\"\027\n\005Reply\022\016\n\006status\030\001 \001(\t2" +
      "G\n\020ConvertPdfToHtml\0223\n\tPdfToHtml\022\022.pdfto" +
      "html.Request\032\020.pdftohtml.Reply\"\000B8\n\033com." +
      "datasahi.pdftohtml.grpcB\016PdfToHtmlProtoP" +
      "\001\210\001\001\242\002\003PTHb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pdftohtml_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pdftohtml_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pdftohtml_Request_descriptor,
        new java.lang.String[] { "Source", "Destination", "Password", });
    internal_static_pdftohtml_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pdftohtml_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pdftohtml_Reply_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
