// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdftohtml.proto

package com.datasahi.pdftohtml.grpc;

public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pdftohtml.Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
