// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdftohtml.proto

package com.datasahi.pdftohtml.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pdftohtml.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source = 1;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 1;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string destination = 2;</code>
   * @return The destination.
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 2;</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
