// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/pdftohtml.proto

package io.grpc.examples.pdftohtml;

public final class PdfToHtmlProto {
  private PdfToHtmlProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pdftohtml_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pdftohtml_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pdftohtml_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pdftohtml_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/proto/pdftohtml.proto\022\tpdftoh" +
      "tml\"@\n\007Request\022\016\n\006source\030\001 \001(\t\022\023\n\013destin" +
      "ation\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\"\027\n\005Reply\022\016" +
      "\n\006status\030\001 \001(\t2G\n\020ConvertPdfToHtml\0223\n\tPd" +
      "fToHtml\022\022.pdftohtml.Request\032\020.pdftohtml." +
      "Reply\"\000B7\n\032io.grpc.examples.pdftohtmlB\016P" +
      "dfToHtmlProtoP\001\210\001\001\242\002\003PTHb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pdftohtml_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pdftohtml_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pdftohtml_Request_descriptor,
        new java.lang.String[] { "Source", "Destination", "Password", });
    internal_static_pdftohtml_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pdftohtml_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pdftohtml_Reply_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
