// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/pdftohtml.proto

package io.grpc.examples.pdftohtml;

public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pdftohtml.Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
